In [2]:
import numpy as np

## numpy array

In [5]:
benimListem = [20,30,40]

In [7]:
type(benimListem)

list

In [9]:
np.array(benimListem)

array([20, 30, 40])

In [11]:
matrixListesi = [[10,20,30],[20,30,40], [30,40,50]]

In [13]:
matrixListesi[1][0]

20

In [15]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [18]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [40]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

## eye

In [45]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [48]:
np.random.randn(8)

array([-1.24049457,  0.21463176, -0.19559611,  0.84001963,  0.66219021,
       -0.98932839,  2.65892032,  1.14329762])

In [50]:
np.random.randn(4,4)

array([[-0.55655908, -0.43186917,  0.90822272,  0.9008809 ],
       [ 0.8100474 , -1.78598441,  0.52032305, -0.32993864],
       [ 0.56667561, -0.70143181,  0.86419598, -0.13868553],
       [ 0.28048798,  2.31397895, -0.597775  , -0.50722577]])

In [52]:
np.random.randint(1,10)

2

In [54]:
np.random.randint(1,20,5)

array([3, 9, 5, 4, 7])

In [56]:
benimNumpyDizim = np.arange(30)

In [58]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
benimRandomDizim = np.random.randint(0,100,30)

In [62]:
benimRandomDizim

array([66, 49, 92, 55,  3, 66, 33, 98, 65, 98, 84, 30, 87, 61, 51, 10, 15,
       74, 97, 54,  2, 90, 97, 48, 70, 71, 67, 41,  8, 29])

## Numpy dizi methodları

In [67]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
benimNumpyDizim.max()

np.int64(29)

In [71]:
benimRandomDizim.max()

np.int64(98)

In [73]:
benimRandomDizim.min()

np.int64(2)

In [81]:
benimRandomDizim.argmax()

np.int64(7)

In [83]:
benimRandomDizim.argmin()

np.int64(20)

In [85]:
benimNumpyDizim.shape

(30,)

In [87]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [91]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])